# Generated by Django 5.1.5 on 2025-01-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('decision_1', models.CharField(max_length=255)),
                ('decision_2', models.CharField(max_length=255)),
                ('decision_1_outcome', models.TextField()),
                ('decision_2_outcome', models.TextField()),
            ],
        ),
    ]
