# Generated by Django 5.1.5 on 2025-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='decision_1_outcome',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='decision_2_outcome',
        ),
        migrations.AddField(
            model_name='scenario',
            name='outcomes',
            field=models.JSONField(default=list),
        ),
    ]
